"""empty message

Revision ID: 78d31036bd66
Revises: 9fe2dd4228cf
Create Date: 2024-07-04 21:46:05.216746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78d31036bd66'
down_revision = '9fe2dd4228cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.drop_column('favorite_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorite_name', sa.VARCHAR(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
